---
name: test-network-org1
version: 1.0.0
client:
  organization: Org1
  connection:
    timeout:
      peer:
        endorser: "300"
organizations:
  Org1:
    mspid: Org1MSP
    peers:
      - peer0.org1.example.com
      - peer1.org1.example.com
    certificateAuthorities:
      - ca.org1.example.com
peers:
  peer0.org1.example.com:
    url: grpcs://localhost:7051
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
          MIICFzCCAb2gAwIBAgIUeCh3Wu2Wqd5CFQ3YXAVdysoHxiIwCgYIKoZIzj0EAwIw
          aDELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMRQwEgYDVQQK
          EwtIeXBlcmxlZGdlcjEPMA0GA1UECxMGRmFicmljMRkwFwYDVQQDExBmYWJyaWMt
          Y2Etc2VydmVyMB4XDTIwMTEwMTEwNTkwMFoXDTM1MTAyOTEwNTkwMFowaDELMAkG
          A1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMRQwEgYDVQQKEwtIeXBl
          cmxlZGdlcjEPMA0GA1UECxMGRmFicmljMRkwFwYDVQQDExBmYWJyaWMtY2Etc2Vy
          dmVyMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEUKSuX8aOkoVOMqUSMrxTfeWs
          jBgTdBz3JHVhgHTDr3DEb49iH66e2GsHkp1PBBcTR+phTM6evYg+uYdOTgJBPKNF
          MEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYDVR0OBBYE
          FLCgJHjvNS/JGiAZYy4wSxHxfsoqMAoGCCqGSM49BAMCA0gAMEUCIQCFpbACTHKi
          0Uv880mc7/EsaRqggVPWMhmJ0Jaehkgg8wIgPviMjFyAekLSXqWx9SKPfnuOAQkp
          YwwKuoirZZMkPgg=
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
      hostnameOverride: peer0.org1.example.com
  peer1.org1.example.com:
    url: grpcs://localhost:${P1PORT}
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
          MIICFzCCAb2gAwIBAgIUeCh3Wu2Wqd5CFQ3YXAVdysoHxiIwCgYIKoZIzj0EAwIw
          aDELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMRQwEgYDVQQK
          EwtIeXBlcmxlZGdlcjEPMA0GA1UECxMGRmFicmljMRkwFwYDVQQDExBmYWJyaWMt
          Y2Etc2VydmVyMB4XDTIwMTEwMTEwNTkwMFoXDTM1MTAyOTEwNTkwMFowaDELMAkG
          A1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMRQwEgYDVQQKEwtIeXBl
          cmxlZGdlcjEPMA0GA1UECxMGRmFicmljMRkwFwYDVQQDExBmYWJyaWMtY2Etc2Vy
          dmVyMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEUKSuX8aOkoVOMqUSMrxTfeWs
          jBgTdBz3JHVhgHTDr3DEb49iH66e2GsHkp1PBBcTR+phTM6evYg+uYdOTgJBPKNF
          MEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYDVR0OBBYE
          FLCgJHjvNS/JGiAZYy4wSxHxfsoqMAoGCCqGSM49BAMCA0gAMEUCIQCFpbACTHKi
          0Uv880mc7/EsaRqggVPWMhmJ0Jaehkgg8wIgPviMjFyAekLSXqWx9SKPfnuOAQkp
          YwwKuoirZZMkPgg=
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer1.org1.example.com
      hostnameOverride: peer1.org1.example.com
certificateAuthorities:
  ca.org1.example.com:
    url: https://localhost:7054
    caName: ca-org1
    tlsCACerts:
      pem:
        - |
          -----BEGIN CERTIFICATE-----
          MIICFzCCAb2gAwIBAgIUeCh3Wu2Wqd5CFQ3YXAVdysoHxiIwCgYIKoZIzj0EAwIw
          aDELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMRQwEgYDVQQK
          EwtIeXBlcmxlZGdlcjEPMA0GA1UECxMGRmFicmljMRkwFwYDVQQDExBmYWJyaWMt
          Y2Etc2VydmVyMB4XDTIwMTEwMTEwNTkwMFoXDTM1MTAyOTEwNTkwMFowaDELMAkG
          A1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMRQwEgYDVQQKEwtIeXBl
          cmxlZGdlcjEPMA0GA1UECxMGRmFicmljMRkwFwYDVQQDExBmYWJyaWMtY2Etc2Vy
          dmVyMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEUKSuX8aOkoVOMqUSMrxTfeWs
          jBgTdBz3JHVhgHTDr3DEb49iH66e2GsHkp1PBBcTR+phTM6evYg+uYdOTgJBPKNF
          MEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYDVR0OBBYE
          FLCgJHjvNS/JGiAZYy4wSxHxfsoqMAoGCCqGSM49BAMCA0gAMEUCIQCFpbACTHKi
          0Uv880mc7/EsaRqggVPWMhmJ0Jaehkgg8wIgPviMjFyAekLSXqWx9SKPfnuOAQkp
          YwwKuoirZZMkPgg=
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
